import Link from 'next/link';
import { Arrow, Brand } from './brand';
import { site } from '@/lib/site';
export function JsonLd({data}:{data:unknown}){return <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(data).replace(/</g,'\\u003c')}}/>;}
export function Breadcrumbs({items}:{items:{name:string;href:string}[]}){const all=[{name:'Home',href:'/'},...items];return <><nav aria-label="Breadcrumb" className="breadcrumbs"><ol>{all.map((i,n)=><li key={i.href}>{n<all.length-1?<Link href={i.href}>{i.name}</Link>:<span aria-current="page">{i.name}</span>}</li>)}</ol></nav><JsonLd data={{'@context':'https://schema.org','@type':'BreadcrumbList',itemListElement:all.map((i,n)=>({'@type':'ListItem',position:n+1,name:i.name,item:site.url+i.href}))}}/></>;}
export function Faq({items}:{items:readonly(readonly[string,string])[]}){return <><div className="faq-list">{items.map(([q,a])=><details key={q}><summary>{q}<span aria-hidden="true">+</span></summary><p>{a}</p></details>)}</div><JsonLd data={{'@context':'https://schema.org','@type':'FAQPage',mainEntity:items.map(([q,a])=>({'@type':'Question',name:q,acceptedAnswer:{'@type':'Answer',text:a}}))}}/></>;}
export function Cta(){return <section className="cta-section"><div className="container cta-inner"><div><p className="eyebrow">LET’S TAKE CARE OF IT</p><h2>A project in mind?<br/><em>Start with a conversation.</em></h2></div><div><Link href="/request-a-quote" className="button button-light">Request a quote <Arrow diagonal/></Link><a className="cta-phone" href={`tel:${site.tel}`}>{site.phone}</a></div></div></section>;}
export function PageIntro({eyebrow,title,description,crumbs}:{eyebrow:string;title:string;description:string;crumbs:{name:string;href:string}[]}){return <section className="page-intro"><div className="container"><Breadcrumbs items={crumbs}/><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p className="lead">{description}</p></div></section>;}
export function Footer(){return <><footer className="site-footer"><div className="container"><div className="footer-grid"><div><Link href="/" aria-label="Saeed Contracting home"><Brand large/></Link><p>Professional service.<br/>Quality work.</p><p className="muted">North Vancouver & Greater Vancouver<br/>Residential · Strata · Commercial</p></div><div><h2>Explore</h2><Link href="/services">Our services</Link><Link href="/service-areas">Where we work</Link><Link href="/about">About Saeed Contracting</Link><Link href="/request-a-quote">Request a quote</Link></div><div><h2>Let’s talk</h2><a href={`tel:${site.tel}`}>{site.phone}</a><a href={`mailto:${site.email}`}>{site.email}</a><Link href="/contact">Contact details <Arrow diagonal/></Link></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Saeed Contracting</span><span>Built for a stronger tomorrow.</span><Link href="/privacy">Privacy</Link></div></div></footer><nav className="mobile-cta" aria-label="Quick contact"><a href={`tel:${site.tel}`}>Call {site.phone}</a><Link href="/request-a-quote">Request a quote <Arrow diagonal/></Link></nav></>;}
